exchange:
  binance:
    host: "api.binance.com"
    hostWebsocket: "stream.binance.com:9443"
    apiKey: "ALgnbBWSULTIELga8J8Rfpz22ooxVwsZkeIis6BVPVE7ZoWnrNxR8n2LILzajjjf"
    apiSecret: "EF6FLsNGHhWx4II2Dr8jZsh7g1giV6O3LUqWFenT79rv6odrQgrYvUZsvPBAvJIm"

arbitrator:
  stableCoins:
    - USDT
  majorCoins:
    - BTC
  shitCoins:
    - DOGE
    - SOL
