exchange:
  binance:
    host: "testnet.binance.vision"
    hostWebsocket: "testnet.binance.vision"
    apiKey: "LMcxKRKNrCnT2WubqGEnN3ijd6jREBameZYNtXhmnH5bsznGKLlUk63ga4fEkIT8"
    apiSecret: "iKl5WBPoVYR8VF4jOPdYKGzyKf4LwFkW6NiSe6tTjx8Oq7mloYxN4xuWtlyFeJJT"

arbitrator:
  stableCoins:
    - USDT
  majorCoins:
    - BTC
    - ETH
  shitCoins:
    - DOGE
    - SHIB
