ignoreUnsupportedSymbols: true
notifyOrderbookUpdateFailure: true

music:
  playMusic: false
  trackName: "Blue moon"
  trackFile: "music/blue_moon.wav"

exchange:
  binance:
    host: "api.binance.com"
    hostWebsocket: "stream.binance.com:9443"
    apiKey: "ALgnbBWSULTIELga8J8Rfpz22ooxVwsZkeIis6BVPVE7ZoWnrNxR8n2LILzajjjf"
    apiSecret: "EF6FLsNGHhWx4II2Dr8jZsh7g1giV6O3LUqWFenT79rv6odrQgrYvUZsvPBAvJIm"

notificator:
  host: api.telegram.org
  token: 5796758875:AAFzrBfIAe-ueMbsfOuaaCfUSUcAuxt8kFw
  chatId: -820535926

storage:
  url: jdbc:postgresql://localhost:5432/huckster
  user: postgres
  password: postgres

arbitrator:
  stableCoins:
    - USDT
  majorCoins:
    - BTC
  shitCoins:
    - XRP
    - DOGE
    - SOL

scam:
  minArbitrageProfit: 1.01
